# Generated by Django 5.1.4 on 2025-01-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_Artist_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artist_name', models.TextField()),
                ('Artist_name_en', models.TextField()),
                ('sex', models.CharField(max_length=200)),
                ('category', models.TextField()),
                ('Albums', models.TextField()),
                ('Melon_ID', models.CharField(max_length=6)),
                ('Apple_url', models.TextField()),
                ('Spotify_ID', models.CharField(max_length=22)),
                ('Youtube_ID', models.CharField(max_length=24)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
