# Generated by Django 5.1.4 on 2025-01-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_artist_profile',
            name='Artist_ID',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
