# Generated by Django 5.1.4 on 2025-01-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0002_create_artist_profile_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_artist_profile',
            name='Artist_image',
            field=models.ImageField(blank=True, upload_to='Artist_images'),
        ),
    ]
