# Generated by Django 5.1.4 on 2025-01-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0003_create_artist_profile_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Albums',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Apple_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Artist_name_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Melon_ID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Spotify_ID',
            field=models.CharField(blank=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Youtube_ID',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
