# Generated by Django 5.1.4 on 2025-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0004_alter_create_artist_profile_albums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.TextField()),
            ],
        ),
    ]
