# Generated by Django 5.1.4 on 2025-01-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0005_album_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='album_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_Category', models.TextField()),
            ],
        ),
    ]
