# Generated by Django 5.1.4 on 2025-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='rightholder_cr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True)),
                ('user_code', models.TextField(blank=True)),
                ('user_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('bank_name', models.TextField(blank=True)),
                ('account_number', models.TextField(blank=True)),
                ('account_holder', models.TextField(blank=True)),
                ('user_level', models.TextField(blank=True)),
                ('user_type', models.TextField(blank=True)),
                ('registration_num', models.TextField(blank=True)),
                ('contract_date', models.TextField(blank=True)),
                ('expiration_date', models.TextField(blank=True)),
            ],
        ),
    ]
