# Generated by Django 5.1.4 on 2025-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0008_rightholder_cr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightholder_cr',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rightholder_cr',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
