# Generated by Django 5.1.4 on 2025-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0009_rightholder_cr_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rightholder_cr',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rightholder_cr',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
