# Generated by Django 5.1.4 on 2025-01-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0012_rightholder_cr_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_artist_profile',
            name='bugs_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='flo_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='genie_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='vibe_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rightholder_cr',
            name='albums',
            field=models.TextField(blank=True),
        ),
    ]
