# Generated by Django 5.1.4 on 2025-01-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0014_accounting_base_album_rightholder_cr_album_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rightholder_cr',
            name='albums',
        ),
    ]
