# Generated by Django 5.1.4 on 2025-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0015_remove_rightholder_cr_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightholder_cr',
            old_name='album',
            new_name='albums',
        ),
    ]
