# Generated by Django 5.1.4 on 2025-02-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0016_rename_album_rightholder_cr_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting_base',
            name='Settlement_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounting_base',
            name='Settlement_rate',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='accounting_base',
            name='Settlement_user',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Albums',
            field=models.TextField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rightholder_cr',
            name='albums',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='rightholder_cr',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
