# Generated by Django 5.1.4 on 2025-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0017_alter_accounting_base_settlement_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='feat_main_artist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='with_main_artist',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='artist_etc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='featAlbums',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='create_artist_profile',
            name='withAlbums',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Albums',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='Melon_ID',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='create_artist_profile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
