# Generated by Django 5.1.4 on 2025-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincms', '0018_album_feat_main_artist_album_with_main_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to='album_data'),
        ),
        migrations.AlterField(
            model_name='accounting_base',
            name='Album_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accounting_base',
            name='rightholder_code',
            field=models.TextField(),
        ),
    ]
